### ISSUE TITLE
You can add your own searches to "searches.js"

### ISSUE THREAD

**Issue by cecoates** [tinytacoteam/zazu-fallback#3]
If anyone is curious, you can add your own custom searches by editing the searches.js file.

After the last search in the list, let's say:

`  youtube: { name: 'YouTube', url: 'https://www.youtube.com/results?search_query='}
`

Add a comma:

`youtube: { name: 'YouTube', url: 'https://www.youtube.com/results?search_query='},
`

And then your own search. For example, if you had setup a custom search in Chrome for Google Cache, it would look like this:

`https://webcache.googleusercontent.com/search?q=cache:%s
`

So remove the %s, and add it in your own entry, like:

` gcache: { name: 'Webpage Cache', url: 'https://webcache.googleusercontent.com/search?q=cache:'}
`

Make sure not to put a comma after the last search, or Zazu will not be pleased. It should look like this following the above examples:

```
  youtube: { name: 'YouTube', url: 'https://www.youtube.com/results?search_query='},
  gcache: { name: 'Webpage Cache', url: 'https://webcache.googleusercontent.com/search?q=cache:'}
}

module.exports = searches
```

If you want to add an icon, add a 256x256 png in the "assets" folder with the same name as your custom search. In this example, gcache.png. I just copied the google.png already in there and renamed it.

Finally, you want to add it to your .zazurc.json:

```
{
      "name": "tinytacoteam/zazu-fallback",
      "variables": {
        "rootSearches": [
          "google",
          "gh",
         "gcache"
        ]
      }
}
```

Now you'll need to update the plugins AND reload config (so it knows you want to use that search).

Then, you can launch Zazu, type "gcache arstechnica.com", and get the Google web cache for that site.

![screenshot from 2017-01-14 20-45-19](https://cloud.githubusercontent.com/assets/10121835/21959861/8719ffb6-da9a-11e6-90d8-fbf61c6ab490.png)

If you added a stray }, ], or comma anywhere, you'll get errors and have to double-check your edits.

I use lots of custom searches specifically for my work, so this is handy. It'd be neat if this was configurable from the .zazurc.json, but it has a lot of pieces. Maybe folks who want their own custom searches would be comfortable doing these edits anyway.

**Comment by bayleedev** [comment]
Is there a reason you closed this? I do like the idea of this feature.
