### ISSUE TITLE
Increase The Number Of Search Results

### ISSUE THREAD

**Issue by Koolstr** [tinytacoteam/zazu-fallback#8]
What can be done to increase the number of fallback engines visible in Zazu, each time I search? Right now, only 7 results appear. I would like to see more/set my own number, since scrolling through the fallback search engines can be tedious and slow. At the very least, instead of an option, it should be set by default to a larger number of results.

[I asked about this under Zazu itself](https://github.com/tinytacoteam/zazu/issues/295#issuecomment-304968112), but they said the number of search results is controlled by individual plugins.

**Comment by bayleedev** [comment]
This plugin returns a result for each `rootSearches ` you have defined, if you want less results you could define less `rootSearches`.

If you want some custom ones or to add new ones you can also do that.

Both of these processes are talked about in the [readme](https://github.com/tinytacoteam/zazu-fallback#installing). A little further down there is a section about what searches are pre-packaged.

Does this answer your question?

**Comment by Koolstr** [comment]
I have 13 defined under `rootSearches`. Yet only 7 of those are visible at a time. There is a scroll bar and I have to scroll to see/reach the other lower defined fallback searches. I would like it to show all of my fallback searches without having to use a scroll bar, i.e., have all the definitions visible at the same time.

**Comment by bayleedev** [comment]
Oh, I misunderstood what you were wanting. The height of zazu is currently dictated by a [single number set to 400](https://github.com/tinytacoteam/zazu/blob/master/app/background.js#L83). We could possibly make this configurable but it would not be the same as `display 13 results`.

The reason is because the height of the search bar and the height of the results are dictated by the theme you picked. So a "possible fix" could be to simply modify your theme to have shorter results, or a lot higher size.

By giving users control over the height wouldn't be bad, as long as it defaults, but giving them control over the width could potentially break some themes.

**Comment by Koolstr** [comment]
I think I understand what you mean. So is there anything that can be done about it? No way to work around this?

**Comment by bayleedev** [comment]
The core could either have an adjustable height, or the theme you pick could have smaller result items. Let me know if you need any help with the core change :+1:

**Comment by Koolstr** [comment]
I think increasing the core height would be the better & more stable approach. If you are suggesting that I try to change the height value in the `background.js` file in my local installation, I will need help. One cannot reverse engineer an `.exe` and I do not see a way to change it before compiling it, nor can I find the `.js` anywhere, so it must be within the executable, I presume. How do you mean for me to change the core height myself?

On a side point: If you think about it, the core mechanic behind the current height approach is shoddy and non-dynamic. It leaves no room for modifications without messing things up, and it is implemented in a way very similar conceptually to how one would add padding to a css element to align it right where you need it. This is not ideal; like all good and well-thought-out code, it should be at the very least modular and at best dynamic. Hence. I suggest making large revisions to the way Zazu renders itself, so that it can be a more user-friendly and visibly reliable application. :)

**Comment by bayleedev** [comment]
@Koolstr If you base it off of configuration this should be easy.

Here is an example of us using the configuration to set a variable. Simply come up with a new variable and you can reference it similar to this:

https://github.com/tinytacoteam/zazu/blob/master/app/background.js#L77

Just a few lines below we create the window, simply use this variable or default to 400.

https://github.com/tinytacoteam/zazu/blob/master/app/background.js#L83-L84

I don't think you'll need a test for this, but it would be great if you could document it.

**Comment by Koolstr** [comment]
My question is, how do I make a modification in my installation? How do I modify that background.js file and have it instanced in my Zazu installation?

**Comment by bayleedev** [comment]
@Koolstr if you clone the repo you can build it on your environment using `npm run release` to re-create it.

**Comment by Koolstr** [comment]
That's what I needed to know. Thanks for telling me; I'll give it a try soon.

**Comment by Koolstr** [comment]
Sorry it took so long. I cloned the repo, modified the configuration and background JS files, recompiled with npm, but I don't notice any difference. Does the new version end up in the /dist/win-unpacked/ directory inside the cloned repo after the npm command? Even running the /dist/zazu-setup.exe does not give me a version that looks in any way modified from the original. Am I missing something or doing something wrong?

**Comment by bayleedev** [comment]
Can you create a pr with your changes so I can see what you've started? I can better help debug then.

**Comment by Koolstr** [comment]
Sure thing. Thanks for checking it out.

**Comment by Koolstr** [comment]
I know it's been a while, but simply reporting back with an update.

This has been resolved, with my PR with the patch finally being merged into Zazu's master branch: https://github.com/tinytacoteam/zazu/pull/300
